"""init

Revision ID: 5fa60d0ab469
Revises:
Create Date: 2024-04-01 23:49:28.552515

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fa60d0ab469"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claim",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "record",
        sa.Column("service_date", sa.DateTime(), nullable=False),
        sa.Column(
            "submitter_procedure", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("quadrant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("group_plan", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subscriber_id", sa.Integer(), nullable=False),
        sa.Column("provider_npi", sa.Integer(), nullable=False),
        sa.Column("provider_fees", sa.Float(), nullable=False),
        sa.Column("allowed_fees", sa.Float(), nullable=False),
        sa.Column("member_coinsurance", sa.Float(), nullable=False),
        sa.Column("member_copay", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_record_subscriber_id"), "record", ["subscriber_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_record_subscriber_id"), table_name="record")
    op.drop_table("record")
    op.drop_table("claim")
    # ### end Alembic commands ###
