"""rename-submitted-proc

Revision ID: b85542055214
Revises: 5fa60d0ab469
Create Date: 2024-04-02 00:51:01.457072

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b85542055214"
down_revision: str | None = "5fa60d0ab469"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "record",
        sa.Column(
            "submitted_procedure", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_column("record", "submitter_procedure")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "record",
        sa.Column(
            "submitter_procedure", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("record", "submitted_procedure")
    # ### end Alembic commands ###
